-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


DROP TABLE IF EXISTS public.users;
DROP TABLE IF EXISTS public.tasks;

CREATE TABLE IF NOT EXISTS public.users
(
    user_id serial NOT NULL,
    user_name character varying NOT NULL,
    password character varying NOT NULL,
    PRIMARY KEY (user_id)
);


CREATE TABLE IF NOT EXISTS public.tasks
(
    task_id serial NOT NULL,
    user_id serial NOT NULL,
    title character varying NOT NULL,
    done boolean NOT NULL
);

ALTER TABLE IF EXISTS public.tasks
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;